// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: F1Grpc.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace F1GrpcServer {
  public static partial class F1Grpc
  {
    static readonly string __ServiceName = "F1Grpc";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::F1GrpcServer.DriversChampionshipsRequest> __Marshaller_DriversChampionshipsRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::F1GrpcServer.DriversChampionshipsRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::F1GrpcServer.DriversChampionshipsResponse> __Marshaller_DriversChampionshipsResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::F1GrpcServer.DriversChampionshipsResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::F1GrpcServer.ConstructorsChampionshipRequest> __Marshaller_ConstructorsChampionshipRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::F1GrpcServer.ConstructorsChampionshipRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::F1GrpcServer.ConstructorsChampionshipResponse> __Marshaller_ConstructorsChampionshipResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::F1GrpcServer.ConstructorsChampionshipResponse.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::F1GrpcServer.DriversChampionshipsRequest, global::F1GrpcServer.DriversChampionshipsResponse> __Method_GetDriversChampionship = new grpc::Method<global::F1GrpcServer.DriversChampionshipsRequest, global::F1GrpcServer.DriversChampionshipsResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetDriversChampionship",
        __Marshaller_DriversChampionshipsRequest,
        __Marshaller_DriversChampionshipsResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::F1GrpcServer.ConstructorsChampionshipRequest, global::F1GrpcServer.ConstructorsChampionshipResponse> __Method_GetConstructorsChampionship = new grpc::Method<global::F1GrpcServer.ConstructorsChampionshipRequest, global::F1GrpcServer.ConstructorsChampionshipResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetConstructorsChampionship",
        __Marshaller_ConstructorsChampionshipRequest,
        __Marshaller_ConstructorsChampionshipResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::F1GrpcServer.F1GrpcReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of F1Grpc</summary>
    [grpc::BindServiceMethod(typeof(F1Grpc), "BindService")]
    public abstract partial class F1GrpcBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::F1GrpcServer.DriversChampionshipsResponse> GetDriversChampionship(global::F1GrpcServer.DriversChampionshipsRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::F1GrpcServer.ConstructorsChampionshipResponse> GetConstructorsChampionship(global::F1GrpcServer.ConstructorsChampionshipRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for F1Grpc</summary>
    public partial class F1GrpcClient : grpc::ClientBase<F1GrpcClient>
    {
      /// <summary>Creates a new client for F1Grpc</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public F1GrpcClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for F1Grpc that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public F1GrpcClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected F1GrpcClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected F1GrpcClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::F1GrpcServer.DriversChampionshipsResponse GetDriversChampionship(global::F1GrpcServer.DriversChampionshipsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetDriversChampionship(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::F1GrpcServer.DriversChampionshipsResponse GetDriversChampionship(global::F1GrpcServer.DriversChampionshipsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetDriversChampionship, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::F1GrpcServer.DriversChampionshipsResponse> GetDriversChampionshipAsync(global::F1GrpcServer.DriversChampionshipsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetDriversChampionshipAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::F1GrpcServer.DriversChampionshipsResponse> GetDriversChampionshipAsync(global::F1GrpcServer.DriversChampionshipsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetDriversChampionship, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::F1GrpcServer.ConstructorsChampionshipResponse GetConstructorsChampionship(global::F1GrpcServer.ConstructorsChampionshipRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetConstructorsChampionship(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::F1GrpcServer.ConstructorsChampionshipResponse GetConstructorsChampionship(global::F1GrpcServer.ConstructorsChampionshipRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetConstructorsChampionship, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::F1GrpcServer.ConstructorsChampionshipResponse> GetConstructorsChampionshipAsync(global::F1GrpcServer.ConstructorsChampionshipRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetConstructorsChampionshipAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::F1GrpcServer.ConstructorsChampionshipResponse> GetConstructorsChampionshipAsync(global::F1GrpcServer.ConstructorsChampionshipRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetConstructorsChampionship, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override F1GrpcClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new F1GrpcClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(F1GrpcBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetDriversChampionship, serviceImpl.GetDriversChampionship)
          .AddMethod(__Method_GetConstructorsChampionship, serviceImpl.GetConstructorsChampionship).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, F1GrpcBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetDriversChampionship, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::F1GrpcServer.DriversChampionshipsRequest, global::F1GrpcServer.DriversChampionshipsResponse>(serviceImpl.GetDriversChampionship));
      serviceBinder.AddMethod(__Method_GetConstructorsChampionship, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::F1GrpcServer.ConstructorsChampionshipRequest, global::F1GrpcServer.ConstructorsChampionshipResponse>(serviceImpl.GetConstructorsChampionship));
    }

  }
}
#endregion
