name: My first workflow
on: 
  push:
    branches:
      - main
jobs:
  first_job:
    name: 123 test
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello world from repo: ${{github.actor}}."  
          echo "Current branch is: ${{github.ref}}."
      - name: Checkout
        uses: actions/checkout@v6.0.2
      - run: tree
  Test:
    runs-on: ubuntu-latest
    environment: Test
    needs: first_job
    steps:
      - run: |
          echo "Hello  from ${{ github.actor }}."
          echo "My secret is ."
  Production:
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: https://writeabout.net
    needs: Test
      
    
